# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: apt install jq

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          newVirusTests=$(curl "https://api.coronavirus.data.gov.uk/v2/data?areaType=overview&metric=newVirusTests&format=json" | jq .body[0].newVirusTests)
          newCasesByPublishDate=$(curl "https://api.coronavirus.data.gov.uk/v2/data?areaType=overview&metric=newCasesByPublishDate&format=json" | jq .body[0].newCasesByPublishDate)
          newAdmissions=$(curl "https://api.coronavirus.data.gov.uk/v2/data?areaType=overview&metric=newAdmissions&format=json" | jq .body[0].newAdmissions)
          newDeathsByPublishDate=$(curl "https://api.coronavirus.data.gov.uk/v2/data?areaType=overview&metric=newDeathsByPublishDate&format=json" | jq .body[0].newDeathsByPublishDate)

          base64 file.pptx -w 0 > fileB64

          reqbody=$(jq -n --arg newVirusTests $newVirusTests --arg newCasesByPublishDate $newCasesByPublishDate --arg newAdmissions $newAdmissions --arg newDeathsByPublishDate $newDeathsByPublishDate --rawfile pptxBase64 fileB64 '{
              "Data": {
                  "newVirusTests": $newVirusTests,
                  "newCasesByPublishDate": $newCasesByPublishDate,
                  "newAdmissions": $newAdmissions,
                  "newDeathsByPublishDate": $newDeathsByPublishDate
              },
              "PptxByte64": $pptxBase64
          }')

          echo $reqbody > input.json

          curl -H "Content-Type: application/json" -X POST -d @input.json https://slidetemplater.azurewebsites.net/api/GeneratePptx > output.pptx

          rm fileB64
          rm input.json
